// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HitCounter } from "./HitCounter";

export type ActivityData = { hitCounters: Array<HitCounter>, conntrackCurrent: number, conntrackMax: number, };
