// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplyResult = { success: boolean, safetyTimerActive: boolean, safetyTimerExpiry: number | null, remoteJobId: string | null, safetyTimerMechanism: string | null, externalChainWarning: string | null, };
