// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChainTraversal = { table: string, chain: string, rulesEvaluated: number, matchedRuleIndex: number | null, };
