// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainOwnerGroup } from "./ChainOwnerGroup";

export type CoexistenceProfile = { owners: Array<ChainOwnerGroup>, totalChains: number, appManagedChains: number, externalChains: number, };
