// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single connection tracking table entry.
 */
export type ConntrackEntry = { protocol: string, sourceIp: string, destIp: string, sourcePort: number, destPort: number, state: string, ttl: number, };
