// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection tracking table usage.
 */
export type ConntrackUsage = { current: number, max: number, percent: number, };
