// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single change between two rulesets.
 */
export type DiffEntry = { "type": "added", chain: string, rule_raw: string, position: number, } | { "type": "removed", chain: string, rule_raw: string, position: number, } | { "type": "modified", chain: string, position: number, old_raw: string, new_raw: string, } | { "type": "policyChanged", chain: string, old_policy: string, new_policy: string, } | { "type": "chainAdded", name: string, } | { "type": "chainRemoved", name: string, };
