// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffEntry } from "./DiffEntry";

export type DriftCheckResult = { drifted: boolean, addedRules: number, removedRules: number, modifiedRules: number, changes: Array<DiffEntry>, };
