// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DualStackDivergence = { diverged: boolean, v4OnlyChains: Array<string>, v6OnlyChains: Array<string>, ruleCountV4: number, ruleCountV6: number, };
