// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DuplicateCheckResult = { isDuplicate: boolean, existingRuleId: string | null, similarity: number, };
