// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fail2ban ban entry (one entry per banned IP).
 */
export type Fail2banBan = { jail: string, ip: string, bannedAt: number, expiresAt: number | null, };
