// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-rule packet/byte hit counters from `iptables -L -v -n -x`.
 */
export type HitCounter = { ruleId: string, packets: number, bytes: number, timestamp: number, chain: string, ruleNum: number, target: string, protocol: string, source: string, destination: string, };
