// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IpsetSuggestion = { chain: string, table: string, patternType: string, ruleCount: number, sampleIps: Array<string>, suggestedName: string, estimatedImprovement: string, };
