// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveTraceRequest = { sourceIp: string | null, destIp: string | null, protocol: string | null, destPort: number | null, interfaceIn: string | null, timeoutSecs: number, };
