// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveTraceEvent = { timestamp: string, table: string, chain: string, ruleNum: number, verdict: string, packetInfo: string, };
