// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveTraceEvent } from "./LiveTraceEvent";

export type LiveTraceResult = { events: Array<LiveTraceEvent>, traceRuleInserted: boolean, traceRuleRemoved: boolean, collectionMethod: string, };
