// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersistenceMethod } from "./PersistenceMethod";

export type PersistenceStatus = { method: PersistenceMethod, packageInstalled: boolean, serviceEnabled: boolean, serviceActive: boolean, lastSaved: string | null, };
