// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffEntry } from "./DiffEntry";

/**
 * The result of comparing two rulesets.
 */
export type RulesetDiff = { 
/**
 * Individual change entries.
 */
changes: Array<DiffEntry>, 
/**
 * `true` when every change only affects TR-* chains (safe to apply with
 * `--noflush`).
 */
appChainsOnly: boolean, };
