// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictType } from "./ConflictType";

export type RuleConflict = { type: ConflictType, ruleIdA: string, ruleIdB: string, description: string, };
