// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight metadata for listing snapshots.
 */
export type SnapshotMeta = { id: string, hostId: string, timestamp: number, description: string | null, ruleCount: number, };
