// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConntrackState } from "./ConntrackState";
import type { Direction } from "./Direction";

export type TestPacket = { sourceIp: string, destIp: string, protocol: string, destPort: number | null, interfaceIn: string, direction: Direction, conntrackState: ConntrackState, };
