// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestConnectionResult = { success: boolean, latencyMs: number, iptablesAvailable: boolean, rootAccess: boolean, dockerDetected: boolean, fail2banDetected: boolean, nftablesBackend: boolean, error: string | null, };
