// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestConnectionParams = { hostname: string, port: number, username: string, authMethod: string, keyPath: string | null, };
