// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainTraversal } from "./ChainTraversal";
import type { Verdict } from "./Verdict";

export type TraceResult = { 
/**
 * Whether a specific rule matched (vs falling through to policy/default).
 */
matched: boolean, 
/**
 * The raw text of the matching rule, if any.
 */
matchedRuleId: string | null, 
/**
 * Chain traversal path (serializes as "chain").
 */
chain: Array<ChainTraversal>, verdict: Verdict, explanation: string, nearMisses: Array<string>, };
