// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Human-readable explanation for a common iptables or SSH error.
 */
export type ErrorExplanation = { code: string, title: string, explanation: string, remediation: Array<string>, };
