use crate::iptables::generator::{port_spec_to_string, rule_spec_to_args};
use crate::iptables::types::RuleSpec;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Export rules as a standalone shell script.
///
/// The script uses `iptables-restore --noflush` with the same format as
/// the apply engine, making it safe to run on a host that already has
/// system-managed chains.
pub fn export_shell_script(rules: &[RuleSpec], table: &str) -> String {
    let mut out = String::new();

    out.push_str("#!/bin/bash\n");
    out.push_str("# Traffic Rules — exported iptables rules\n");
    out.push_str("# Generated by Traffic Rules app\n");
    out.push_str("set -euo pipefail\n\n");

    // Generate iptables-restore content
    let restore_content = build_restore_content(rules, table);

    out.push_str("# Apply rules via iptables-restore (atomic)\n");
    out.push_str("cat <<'IPTABLES_RULES' | sudo iptables-restore -w 5 --noflush --counters\n");
    out.push_str(&restore_content);
    out.push_str("IPTABLES_RULES\n\n");
    out.push_str("echo \"Rules applied successfully.\"\n");

    out
}

/// Export rules as an Ansible playbook.
pub fn export_ansible_playbook(rules: &[RuleSpec], hostname: &str) -> String {
    let mut out = String::new();

    out.push_str("---\n");
    out.push_str("# Traffic Rules — exported Ansible playbook\n");
    out.push_str("# Generated by Traffic Rules app\n");
    out.push_str("- name: Apply Traffic Rules iptables configuration\n");
    out.push_str(&format!("  hosts: {}\n", hostname));
    out.push_str("  become: true\n");
    out.push_str("  tasks:\n");

    for (i, rule) in rules.iter().enumerate() {
        let args = rule_spec_to_args(rule);

        // Build the iptables_rule module parameters
        let chain = "TR-INPUT"; // Default chain
        let target = rule
            .target
            .as_ref()
            .map(|t| t.to_string())
            .unwrap_or_else(|| "ACCEPT".to_string());

        let comment = rule
            .comment
            .as_ref()
            .map(|c| c.to_string())
            .unwrap_or_else(|| format!("Rule {}", i + 1));

        out.push_str(&format!("    - name: {}\n", comment));
        out.push_str("      ansible.builtin.iptables:\n");
        out.push_str(&format!("        chain: {}\n", chain));
        out.push_str(&format!("        jump: {}\n", target));

        if let Some(ref proto) = rule.protocol {
            out.push_str(&format!("        protocol: {}\n", proto));
        }

        if let Some(ref src) = rule.source {
            out.push_str(&format!("        source: {}\n", src.addr));
        }

        if let Some(ref dst) = rule.destination {
            out.push_str(&format!("        destination: {}\n", dst.addr));
        }

        if let Some(ref dp) = rule.dest_port {
            out.push_str(&format!(
                "        destination_port: \"{}\"\n",
                port_spec_to_string(dp)
            ));
        }

        if let Some(ref iface) = rule.in_iface {
            out.push_str(&format!("        in_interface: {}\n", iface.name));
        }

        if let Some(ref iface) = rule.out_iface {
            out.push_str(&format!("        out_interface: {}\n", iface.name));
        }

        if let Some(ref comment_text) = rule.comment {
            out.push_str(&format!("        comment: \"{}\"\n", comment_text));
        }

        let _ = args; // args used indirectly above
    }

    out
}

/// Export rules in `iptables-save` format.
///
/// Produces a file that can be applied with `iptables-restore --noflush`.
pub fn export_iptables_save(rules: &[RuleSpec], table: &str) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Traffic Rules app\n");
    out.push_str(&build_restore_content(rules, table));
    out
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Build iptables-restore content with chain reset lines and COMMIT.
fn build_restore_content(rules: &[RuleSpec], table: &str) -> String {
    let mut out = String::new();

    // Collect chain names from rules
    let mut chain_names: std::collections::BTreeSet<String> =
        std::collections::BTreeSet::new();
    // Default chain
    chain_names.insert("TR-INPUT".to_string());

    out.push_str(&format!("*{}\n", table));

    // Emit chain reset lines
    for chain in &chain_names {
        out.push_str(&format!(":{} - [0:0]\n", chain));
    }

    // Emit rules
    for rule in rules {
        let args = rule_spec_to_args(rule);
        out.push_str(&format!("-A TR-INPUT {}\n", args.join(" ")));
    }

    out.push_str("COMMIT\n");
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::iptables::types::*;

    fn make_spec() -> RuleSpec {
        RuleSpec {
            protocol: None,
            protocol_negated: false,
            source: None,
            destination: None,
            in_iface: None,
            out_iface: None,
            matches: vec![],
            target: None,
            target_args: vec![],
            comment: None,
            counters: None,
            fragment: None,
            source_port: None,
            dest_port: None,
            address_family: AddressFamily::V4,
        }
    }

    #[test]
    fn test_export_shell_script() {
        let rules = vec![
            RuleSpec {
                protocol: Some(Protocol::Tcp),
                dest_port: Some(PortSpec::Single(22)),
                target: Some(Target::Accept),
                source: Some(AddressSpec {
                    addr: "10.0.0.0/8".to_string(),
                    negated: false,
                }),
                ..make_spec()
            },
        ];

        let script = export_shell_script(&rules, "filter");
        assert!(script.starts_with("#!/bin/bash\n"));
        assert!(script.contains("iptables-restore"));
        assert!(script.contains("*filter"));
        assert!(script.contains(":TR-INPUT"));
        assert!(script.contains("-A TR-INPUT"));
        assert!(script.contains("COMMIT"));
        assert!(script.contains("-p tcp"));
        assert!(script.contains("--dport 22"));
        assert!(script.contains("-j ACCEPT"));
    }

    #[test]
    fn test_export_ansible_playbook() {
        let rules = vec![
            RuleSpec {
                protocol: Some(Protocol::Tcp),
                dest_port: Some(PortSpec::Single(80)),
                target: Some(Target::Accept),
                comment: Some("Allow HTTP".to_string()),
                ..make_spec()
            },
        ];

        let playbook = export_ansible_playbook(&rules, "webservers");
        assert!(playbook.contains("hosts: webservers"));
        assert!(playbook.contains("become: true"));
        assert!(playbook.contains("ansible.builtin.iptables"));
        assert!(playbook.contains("jump: ACCEPT"));
        assert!(playbook.contains("protocol: tcp"));
        assert!(playbook.contains("destination_port: \"80\""));
        assert!(playbook.contains("Allow HTTP"));
    }

    #[test]
    fn test_export_iptables_save() {
        let rules = vec![
            RuleSpec {
                protocol: Some(Protocol::Tcp),
                dest_port: Some(PortSpec::Multi(vec![80, 443])),
                target: Some(Target::Accept),
                ..make_spec()
            },
        ];

        let save = export_iptables_save(&rules, "filter");
        assert!(save.contains("*filter"));
        assert!(save.contains(":TR-INPUT - [0:0]"));
        assert!(save.contains("-A TR-INPUT"));
        assert!(save.contains("COMMIT"));
    }

    #[test]
    fn test_export_shell_script_empty_rules() {
        let rules: Vec<RuleSpec> = vec![];
        let script = export_shell_script(&rules, "filter");
        assert!(script.contains("*filter"));
        assert!(script.contains("COMMIT"));
        assert!(script.contains(":TR-INPUT"));
    }
}
